# 日志文件
[log]
path = 'tiny-server.log'
level = 'debug'
max_file_size = 1 # MB单位
max_files = 3

# 服务器配置
[server]
port = 9999 # 服务器监听端口
max_thread_num = 2 # 线程池中线程数量

# mysql数据库信息
## notice, dont do bad things !!
[sql]
name = 'dacao'
password = 'qwert'
host = '127.0.0.1'
schema = 'message_board'
table = 'message'
pool_size = 2
